### ISSUE TITLE
Not enough training samples for any cell types at root of cell type hierarchy!

### ISSUE THREAD

**Issue by DanSchnell** [cole-trapnell-lab/garnett#17]
What would be the most likely cause(s) of the "Not enough training samples for any cell types at root of cell type hierarchy!

Dataset I'm working with has 46 clusters, ranging from 11 to 600+ barcodes.  All barcodes have a cluster assignment--no "Unknown"s.

Markers not in db or "Ok - marker_score N/A" have been removed

code:
library(org.Hs.eg.db)
set.seed(260)
marker_file_path <- paste(in1DataPath,"SMART-Markers2.txt",sep="")
SMART_classifier <- train_cell_classifier(cds = SMART_cds,
                                         marker_file = marker_file_path,
                                         db=org.Mm.eg.db,
                                         cds_gene_id_type = "SYMBOL",
                                         num_unknown = 500,
                                         marker_file_gene_id_type = "SYMBOL")

Have tried values of num_unknown from 5 to 1000--all produce the error message (+ some extras w/ 5).

Thanks very much in advance for any guidance!

**Comment by hpliner** [comment]
Hello, are you using the monocle3 branch or the master branch?

**Comment by kchiou** [comment]
@DanSchnell I got a similar error that I chalked up to a mismatch between gene symbols in my cell data set and the gene symbols in another species' marker file. It looks like you loaded a human database (`library(org.Hs.eg.db)`) but used a mouse database (`db=org.Mm.eg.db`) in your train_cell_classifier() call. Assuming that worked (i.e., the mouse database was loaded previously), it looks like you might have a similar mismatch between gene symbols.

**Comment by hy395** [comment]
Hi, I am having a similar issue when using garnett. When garnett is trying to find "good cells" for training, all cells are labeled as "ambiguous". 
After looking into garnett code, I want to confirm whether the following code is correct or a potential bug. In **get_training_sample.R** line 130, first step in determining ambiguity is creating a binary dataframe of cells passing the cutoff for each gene set:
  q <- as.data.frame(total_vals > cutoffs)
Should this be:
q <- as.data.frame(t(t(total_vals) > cutoffs))
instead? since R is operating on columns first?

**Comment by hpliner** [comment]
Hello @hy395, 

Yikes, looks to me like you're right... good catch. I've done a bit of testing and it looks like it didn't show up previously because when the cutoffs are similar (because the overall transformed expression of marker genes across types is similar), the fix doesn't change things much. But perhaps in your and other cases there is a larger discrepancy and fewer of your cells will be labelled ambiguous. In any case, it certainly needed fixing!

The latest version of both master and monocle3 branches now have the fix, and hopefully it improves your results! I will close this issue for the moment, please reopen if you continue to have issues.

**Comment by hy395** [comment]
@hpliner Thanks for fixing!

**Comment by saisomesh2594** [comment]
Hi All,

I am encountering this same issue when trying to build a classifier for immune cells derived from mouse pancreatic tissues.  I have ~8000 cells divided into 14 clusters and the garnett marker file contains markers for each cluster. I have removed duplicate markers and then build a classifier as follows:
`library(garnett)`
`library(org.Mm.eg.db)`
`mouse.classifier <- train_cell_classifier(cds = immune.cds,`
                                        `marker_file = <path to garnett marker file>,`
                                         `db= org.Mm.eg.db,`
                                         `cds_gene_id_type = "ENSEMBL",`
                                         `num_unknown = 50,`
                                         `marker_file_gene_id_type = "SYMBOL")`

I get the following error:  `Not enough training samples for any cell types at root of cell type hierarchy!` with additional error messages.

Do you think it is because of low cell count ? I would assumes to build a classifer, one would need quite a good number of cells!

Thanks,
Somesh
