### ISSUE TITLE
Syntax error '(' at or near line when running check_markers()

### ISSUE THREAD

**Issue by a-solovyev12** [cole-trapnell-lab/garnett#48]
Hello, 

When running the `check_markers()` function, I am getting the following error: 
```
Marker file error. Illegal character '('
Error in self$errorfunc(errtoken) : 
  Marker file error. Syntax error '(' at or near line number 1
Calls: check_markers -> parse_input -> <Anonymous> -> <Anonymous>
```
 
Marker file used has brackets in the names of corresponding cell types, e.g. 
```
>CD16-negative natural killer cell (NK CD16-)
expressed: ENSG00000188404, ENSG00000150045, ...

>CD16-positive natural killer cell (NK CD16+)
expressed: ENSG00000150045, ENSG00000180644, ..., etc. 

```

This marker file was generated as a part of an automated pipeline, and there are no checks for specific aspects of cell type naming. I was wondering if brackets are causing any specific problems? Otherwise I can't see a reason why they should be considered illegal characters. Please let me know what you think. 

Many thanks, 
Andrey

**Comment by hpliner** [comment]
Hi Andrey,
This is definitely a bug related to the automated monocle3-to-garnett functionality. You are correct that the issue here are the parentheses. I'm going to leave this open to be fixed when I get a chance, but in the meantime, go ahead and just open the marker text file that's generated by monocle3 and delete or replace the parentheses.

Hopefully I can get to a better fix in the next few weeks.

Thanks for the report!

**Comment by hpliner** [comment]
I believe this is fixed in the latest version of monocle3. Reinstall and give it a try!
