### ISSUE TITLE
marker_check 

### ISSUE THREAD

**Issue by jhu99** [cole-trapnell-lab/garnett#6]
We have two issues regarding with marker_check.
1. We got many markers with NA marker score. Should we remove these markers in the next step?
2. We remove all markers with >0.5 ambiguity, and run marker_check again. We still get more markers with >0.5 ambiguity. Should me remove these markers again and again?
[a_marker_check.txt](https://github.com/cole-trapnell-lab/garnett/files/3074067/a_marker_check.txt)

**Comment by hpliner** [comment]
1. The NAs should be from negative markers (not expressed). We can't calculate ambiguity scores for negative markers because of high dropout/sparsity. Not a problem to keep them

2. This could be due to a weakness of our current method of testing markers - if you have a gene included that is widely expressed and non-specific, then if will often make other marker genes look ambiguous (the ambiguity score is a ratio of the number of cells made ambiguous over the total number nominated... if a widely expressed gene will nominate lots of cells, bringing it ambiguity down). I'm currently working on a few new metrics for marker quality do deal with this case.

However, it looks to me like your issue may be that a lot of your cell types share markers - i.e. looks like PTPRC is present in all of the root cell types. This could be a function of marker propogation (if propogate = TRUE, then markers for child cell types are considered to also be markers for the parent).

Hope this helps, reopen if not
