### ISSUE TITLE
 Unable to download package

### ISSUE THREAD

**Issue by xu15825503775** [cole-trapnell-lab/garnett#63]
Sorry, when I tried to use this package, I found the command devtools:: install_ Github ("cole trapnell lab/garnett", ref="mono cle3") cannot install this package. The timeout is displayed. Then I went to github to check. I found the reason is "All checks have failed". I hope you can solve this problem as soon as possible

![Uploading image.png…]()

**Comment by hpliner** [comment]
Hello, the 'All checks have failed' code has to do with out continuous integration system and should not cause an issue with your install. I can't see the image you've uploaded, but if it's a timeout error then this likely is an issue with your network. Can you post the error output as text?

**Comment by joaolsf** [comment]
Hello @hpliner , I am also having an issue trying to install devtools::install_github("cole-trapnell-lab/garnett", ref="monocle3"). 
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo cole-trapnell-lab/garnett@monocle3
Skipping 6 packages not available: org.Mm.eg.db, org.Hs.eg.db, DelayedMatrixStats, DelayedArray, Biobase, AnnotationDbi
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/0m/4rwt_z816mlcps48xsc34jvc0000gn/T/RtmpRMyyFm/remotes399556f2f561/cole-trapnell-lab-garnett-65f2c6f/DESCRIPTION’ ...
─  preparing ‘garnett’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘garnett_0.2.20.tar.gz’
   
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
Execution halted
Warning message:
In i.p(...) :
  installation of package '/var/folders/0m/4rwt_z816mlcps48xsc34jvc0000gn/T//RtmpRMyyFm/file399568cbdfdf/garnett_0.2.20.tar.gz' had non-zero exit status

Then I am in a weird cross-roads. I have monocle3 loaded, but because I can't install Garnett with the code above, Garnett is installed with monocle, so both, monocle and monocle3 are loaded in my env. Thus, both functions new_cell_data_set and newCellDataSet work. However, the CDS object generated by the second function can't be visualised. I get the error: Error in vcount(x) : REAL() can only be applied to a 'numeric', not a 'NULL'
Then, if I try to run train_cell_classifier with the CDS object generated by the first function (new_cell_data_set), I get the following error: Error in train_cell_classifier(cds = monocle_cds, marker_file = marker_file_path,  : could not find function "train_cell_classifier".

**Comment by hpliner** [comment]
Hello, Sorry, missed this issue. Have you tried installing via the above when original monocle is not attached (i.e. in a new session)? I'm wondering if this is from some kind of collision

**Comment by hpliner** [comment]
Closing from lack of activity - reopen if still an issue
